<?php
include_once __DIR__."/config.buttons.php";
// Path to the authentication file
$auth_file = '/etc/svxlink/dashboard.auth.ini';

// Create dummy fallback if the file doesn't exist yet
if (!file_exists($auth_file)) {
    $dummy_user = 'svxlink';
    $dummy_pass = 'password';
    $auth_content = "[dashboard]\nauth_user = $dummy_user\nauth_pass = $dummy_pass\n";
    file_put_contents($auth_file, $auth_content);
}

// Parse the INI file
$auth_data = parse_ini_file($auth_file);

// Set constants based on the parsed data (fallback to dummy values if keys missing)
define('PHP_AUTH_USER', $auth_data['auth_user'] ?? 'svxlink');
define('PHP_AUTH_PW', $auth_data['auth_pass'] ?? 'password');
// header lines for information
define("HEADER_CAT","FM-Repeater");
define("HEADER_QTH","null");
define("HEADER_QRG","null");
define("HEADER_SYSOP","");
define("FMNETWORK_EXTRA","");
define("EL_NODE_NR","null");
define("FULLACCESS_OUTSIDE", 0);
define("ADD_BUTTONS", 1);
///Variables for the webpages
define("MODULE_PATH", "");
define("LOGIC_CORE_PATH", "");
define("CFG_DIR", "");
define("TIMESTAMP_FORMAT", "");
define("TIME_FORMAT", "");
define("CARD_SAMPLE_RATE", "");
define("CARD_CHANNELS", "");
define("LOCATION_INFO", "");
define("TYPE", "");
define("RX", "");
define("TX", "");
define("MODULES", "");
define("SHORT_IDENT_INTERVAL", "");
define("LONG_IDENT_INTERVAL", "");
define("IDENT_ONLY_AFTER_TX", "");
define("EXEC_CMD_ON_SQL_CLOSE", "");
define("EVENT_HANDLER", "");
define("RGR_SOUND_DELAY", "");
define("RGR_SOUND_ALWAYS", "");
define("TX_CTCSS", "");
define("MACROS", "");
define("ACTIVATE_MODULE_ON_LONG_CMD", "");
define("QSO_RECORDER", "");
define("ONLINE_CMD", "");
define("ONLINE", "");
define("MUTE_RX_ON_TX", "");
define("MUTE_TX_ON_RX", "");
define("STATE_PTY", "");
define("CTCSS_TO_TG", "");
define("CTCSS_TO_TG_DELAY", "");
define("DNS_DOMAIN", "");
define("HOST_PORT", "");
define("HOST_PRIO", "");
define("HOST_PRIO_INC", "");
define("HOST_WEIGHT", "");
define("JITTER_BUFFER_DELAY", "");
define("DEFAULT_TG", "");
define("MONITOR_TGS", "");
define("TG_SELECT_TIMEOUT", "");
define("TG_SELECT_INHIBIT_TIMEOUT", "");
define("ANNOUNCE_REMOTE_MIN_INTERVAL", "");
define("MUTE_FIRST_TX_LOC", "");
define("MUTE_FIRST_TX_REM", "");
define("TMP_MONITOR_TIMEOUT", "");
define("UDP_HEARTBEAT_INTERVAL", "");
define("QSY_PENDING_TIMEOUT", "");
define("VERBOSE", "");
define("CONNECT_LOGICS", "");
define("DEFAULT_ACTIVE", "");
define("TIMEOUT", "");
define("ACTIVATE_ON_ACTIVITY", "");
define("REC_DIR", "");
define("MIN_TIME", "");
define("MAX_TIME", "");
define("SOFT_TIME", "");
define("MAX_DIRSIZE", "");
define("QSO_TIMEOUT", "");
define("ENCODER_CMD", "");
define("RECEIVERS", "");
define("VOTING_DELAY", "");
define("BUFFER_LENGTH", "");
define("REVOTE_INTERVAL", "");
define("HYSTERESIS", "");
define("SQL_CLOSE_REVOTE_DELAY", "");
define("RX_SWITCH_DELAY", "");
define("COMMAND_PTY", "");
define("TRANSMITTERS", "");
define("HOST", "");
define("TCP_PORT", "");
define("LOG_DISCONNECTS_ONCE", "");
define("CODEC", "");
define("SPEEX_ENC_FRAMES_PER_PACKET", "");
define("SPEEX_ENC_QUALITY", "");
define("SPEEX_ENC_BITRATE", "");
define("SPEEX_ENC_COMPLEXITY", "");
define("SPEEX_ENC_VBR", "");
define("SPEEX_ENC_VBR_QUALITY", "");
define("SPEEX_ENC_ABR", "");
define("SPEEX_DEC_ENHANCER", "");
define("OPUS_ENC_FRAME_SIZE", "");
define("OPUS_ENC_COMPLEXITY", "");
define("OPUS_ENC_BITRATE", "");
define("OPUS_ENC_VBR", "");
define("TX_ID", "");
define("AUDIO_DEV", "");
define("AUDIO_DEV_KEEP_OPEN", "");
define("LIMITER_THRESH", "");
define("PTT_TYPE", "");
define("PTT_PORT", "");
define("PTT_PIN", "");
define("HID_PTT_PIN", "");
define("SERIAL_SET_PINS", "");
define("PTT_GPIOD_CHIP", "");
define("PTT_GPIOD_LINE", "");
define("PTT_HANGTIME", "");
define("CTCSS_LEVEL", "");
define("DTMF_TONE_LENGTH", "");
define("DTMF_TONE_SPACING", "");
define("DTMF_DIGIT_PWR", "");
define("MASTER_GAIN", "");
define("OB_AFSK_ENABLE", "");
define("OB_AFSK_VOICE_GAIN", "");
define("OB_AFSK_LEVEL", "");
define("OB_AFSK_TX_DELAY", "");
define("IB_AFSK_ENABLE", "");
define("IB_AFSK_LEVEL", "");
define("IB_AFSK_TX_DELAY", "");
define("SQL_DET", "");
define("SQL_START_DELAY", "");
define("SQL_HANGTIME", "");
define("SQL_EXTENDED_HANGTIME", "");
define("SQL_EXTENDED_HANGTIME_THRESH", "");
define("SQL_TIMEOUT", "");
define("VOX_FILTER_DEPTH", "");
define("VOX_THRESH", "");
define("CTCSS_MODE", "");
define("CTCSS_SNR_OFFSET", "");
define("CTCSS_SNR_OFFSETS", "");
define("CTCSS_OPEN_THRESH", "");
define("CTCSS_CLOSE_THRESH", "");
define("CTCSS_BPF_LOW", "");
define("CTCSS_BPF_HIGH", "");
define("CTCSS_EMIT_TONE_DETECTED", "");
define("SERIAL_PORT", "");
define("SERIAL_PIN", "");
define("EVDEV_DEVNAME", "");
define("EVDEV_OPEN", "");
define("EVDEV_CLOSE", "");
define("GPIO_PATH", "");
define("GPIO_SQL_PIN", "");
define("SQL_GPIOD_CHIP", "");
define("SQL_GPIOD_LINE", "");
define("SQL_GPIOD_BIAS", "");
define("PTY_PATH", "");
define("HID_SQL_PIN", "");
define("SIGLEV_DET", "");
define("SIGLEV_SLOPE", "");
define("SIGLEV_OFFSET", "");
define("SIGLEV_BOGUS_THRESH", "");
define("TONE_SIGLEV_MAP", "");
define("SQL_SIGLEV_OPEN_THRESH", "");
define("SQL_SIGLEV_CLOSE_THRESH", "");
define("DEEMPHASIS", "");
define("SQL_TAIL_ELIM", "");
define("PREAMP", "");
define("PEAK_METER", "");
define("DTMF_DEC_TYPE", "");
define("DTMF_MUTING", "");
define("DTMF_HANGTIME", "");
define("DTMF_SERIAL", "");
define("DTMF_PTY", "");
define("DTMF_MAX_FWD_TWIST", "");
define("DTMF_MAX_REV_TWIST", "");
define("1750_MUTING", "");
define("SEL5_DEC_TYPE", "");
define("SEL5_TYPE", "");
define("LADSPA_PLUGINS", "");
define("FQ", "");
define("MODULATION", "");
define("WBRX", "");
define("DEV_MATCH", "");
define("PORT", "");
define("CENTER_FQ", "");
define("FQ_CORR", "");
define("GAIN", "");
define("SAMPLE_RATE", "");
define("APRS_SERVER_LIST", "");
define("STATUS_SERVER_LIST", "");
define("LON_POSITION", "");
define("LAT_POSITION", "");
define("FREQUENCY", "");
define("TX_POWER", "");
define("ANTENNA_GAIN", "");
define("ANTENNA_HEIGHT", "");
define("ANTENNA_DIR", "");
define("PATH", "");
define("BEACON_INTERVAL", "");
define("TONE", "");
define("COMMENT", "");
define('AUTHORISED', 'AUTHORISED');
define('UNAUTHORISED', 'UNAUTHORISED');
//
define("SVXCONFPATH", "/etc/svxlink/");
define("SVXCONFIG", "svxlink.conf");
define("SVXLOGPATH", "/var/log/");
define("SVXLOGPREFIX","svxlink.log");
define("CALLSIGN","null");
define("LOGICS","null");
define("REPORT_CTCSS","null");
define("DTMF_CTRL_PTY","null");
define("API","null");
define("FMNET","null");
define("TG_URI","null");
define("NODE_INFO_FILE","/etc/svxlink/node_info.json");
define("RF_MODULE","null");
define("QTH","null");
define("FREQ","null");
define("LOCATION","null");
define("CW_AMP","inCwAmp");
define("CW_PITCH","inCwPitch");
define("CW_CPM","inCwCpm");
define("LINKS","null");
define("AUTH_KEY","password");
define("FMNETWORK","inFmnetwork");
define("DEFAULT_LANG","inReflectorDefaultLang");
define("RGR_DELAY","inRgrDelay");
define("IDLE_INTERVAL_TIME","inIdleIntervalTime");
define("FX_GAIN_NORMAL","inFxGainNormal");
define("FX_GAIN_LOW","inFxGainLow");
define("AUDIO_CHANNEL","inRxAudioChannel");
define("SQL_DELAY","inSqlDelay");
define("HID_DEVICE","inRxHidDevice");
define("HOSTS","null");
define("DATABASES","/var/www/html/databases");

$svxConfigFile = '/etc/svxlink/svxlink.conf';
if (fopen($svxConfigFile, 'r')) {
    $svxconfig = parse_ini_file($svxConfigFile, true, INI_SCANNER_RAW);
    $refApi = isset($svxconfig['ReflectorLogic']['API']) ? $svxconfig['ReflectorLogic']['HOSTS'] : '';
    $fmnetwork = isset($svxconfig['ReflectorLogic']['HOSTS']) ? $svxconfig['ReflectorLogic']['HOSTS'] : '';
    $qth = isset($svxconfig['LocationInfo']['QTH']) ? $svxconfig['LocationInfo']['QTH'] : '';
    $freq = isset($svxconfig['Rx1']['FREQ']) ? $svxconfig['Rx1']['FREQ'] : '';
    $EL_node = isset($svxconfig['LocationInfo']['LOCATION']) ? $svxconfig['LocationInfo']['LOCATION'] : '';
} else {
    $callsign = "NOCALL";
    $fmnetwork = "not registered";
    $EL_node = "unknown";
}
